# Generated by Django 5.0.4 on 2024-04-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                (
                    "pub_date",
                    models.DateTimeField(
                        auto_now_add=True, primary_key=True, serialize=False
                    ),
                ),
            ],
            options={
                "ordering": ["-pub_date"],
            },
        ),
    ]
