# Generated by Django 5.0.4 on 2024-04-23 12:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField(blank=True, null=True)),
                ("update", models.TextField(blank=True, null=True)),
                (
                    "created_at_time",
                    models.TimeField(default=django.utils.timezone.now),
                ),
                (
                    "created_at",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fb_blog.day"
                    ),
                ),
            ],
        ),
    ]
