# Generated by Django 5.0.4 on 2024-04-15 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fb_blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 15, 16, 28, 44, 750395, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
