# Generated by Django 5.0.4 on 2024-04-23 12:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fb_blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="date",
            field=models.DateField(default=django.utils.timezone.now, unique=True),
        ),
    ]
