# Generated by Django 5.0.4 on 2024-04-23 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fb_blog", "0002_alter_day_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={"ordering": ["-created_at", "-created_at_time"]},
        ),
        migrations.AlterModelOptions(
            name="day",
            options={"ordering": ["-date"]},
        ),
    ]
