# Generated by Django 5.0.4 on 2024-04-23 13:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fb_blog", "0003_alter_blogpost_options_alter_day_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterModelOptions(
            name="blogpost",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="created_at_time",
        ),
        migrations.DeleteModel(
            name="Day",
        ),
    ]
